// Re-export shared types เพื่อให้ import ภายใน frontend สั้นลง
export type {
  Employee,
  Department,
  OrgNode,
  Task,
  DocumentItem,
  Approval,
  Customer,
  ServiceType,
  NotificationItem,
  Insight,
  DashboardSummary,
  TrendPoint,
  ReportData,
  Paginated,
  LoadLevel,
  TaskStatus,
  DocStatus,
  CustomerTier,
  InsightType,
  // Google Sheets integration
  CaseRow,
  SheetTabMeta,
  SheetMetadata,
  SheetStatus,
  SheetSideStatus,
  SheetSummary,
  SummaryMetric,
  SummarySource,
  SyncResult,
  SyncAllResult,
  SyncSourceFailure,
  MappingWarning,
  SheetHeadersResult,
  Pagination,
  SheetRowsResult,
  ApiErrorBody,
  HealthResponse,
} from "@tracking-cyd/shared";
